server:
  port: 8081
spring:
  application:
    name: System
  output:
    ansi:
      enabled: always
  #数据库配置
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/Mydb?useSSL=false&serverTimezone=UTC
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      #配置初始化大小、最小、最大线程数
      initial-size: 5
      min-idle: 5
      #CPU核数+1，也可以大些但不要超过20，数据库加锁时连接过多性能下降
      max-active: 20
      #最大等待时间，内网：800，外网：1200（三次握手1s）
      max-wait: 60000
      time-between-eviction-runs-millis: 60000
      # 配置一个连接在池中最大空间时间，单位是毫秒
      min-evictable-idle-time-millis: 300000
      validationQuery: SELECT 1
      testWhileIdle: true
      #设置从连接池获取连接时是否检查连接有效性，true检查，false不检查
      testOnBorrow: true
      #设置从连接池归还连接时是否检查连接有效性，true检查，false不检查
      testOnReturn: true
      #可以支持PSCache（提升写入、查询效率）
      poolPreparedStatements: true
      #配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
      filters: stat,wall,log4j
      #保持长连接
      keepAlive: true
      maxPoolPreparedStatementPerConnectionSize: 20
      useGlobalDataSourceStat: true
      connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=500
  #redis配置
  redis:
    #ip
    host: 127.0.0.1
    #端口
    port: 6379
    #密码（默认为空）
    password:
    #数据库索引（默认为0）
    database: 0
    jedis:
      pool:
        #接池最大连接数（使用负值表示没有限制）
        max-active: 50
        #连接池最大阻塞等待时间（使用负值表示没有限制）
        max-wait: 3000
        #连接池中的最大空闲连接
        max-idle: 20
        #连接池中的最小空闲连接
        min-idle: 2
    #连接超时时间（毫秒）
    timeout: 5000
eureka:
  instance:
    prefer-ip-address: true
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8000/eureka/
logging:
  level:
    com.jt: info
mybatis-plus:
  configuration:
    #关闭下划线转小驼峰
    map-underscore-to-camel-case: false


